#!/bin/bash

echo "START >>>>>>>>>>>>"
echo "AGRG1" $1
echo "AGRG2" $2
echo "AGRG3" $3
echo "AGRG4" $4
echo "AGRG5" $5
echo "AGRG6" $6
echo "AGRG7" $7
echo "AGRG8" $8
echo "AGRG9" $9
echo "AGRG10" $10
echo "AGRG11" $11
echo "AGRG12" $12
#open /Applications/AccuRev/bin/acdiffgui.app --args $1 $2 $3 $4 $5 $6 $7 $8 $9

cp $5 /tmp
BASE=/tmp/$(basename $5)
echo "BASE" $BASE
LOCAL=$6
BASE_NAME=$4
LOCAL_NAME=$2
#/Applications/kdiff3.app/Contents/MacOS/kdiff3 $1 $2 #> /Users/hein/Desktop/hist.txt | subl /Users/hein/Desktop/hist.txt
open /Applications/kdiff3.app --args  -L1 "$BASE_NAME" -L2 "$LOCAL_NAME" $BASE $LOCAL
#less $1
#rm -f $BASE
